package edu.school21.chat.app;

import edu.school21.chat.exceptions.NotSavedSubEntityException;
import edu.school21.chat.models.Chatroom;
import edu.school21.chat.models.Message;
import edu.school21.chat.models.User;
import edu.school21.chat.repositories.*;

import java.sql.Connection;
import java.time.LocalDateTime;

import static edu.school21.chat.util.InitConnection.init_connection;

public class Program
{
	public static void main(String[] args)
	{
		Connection connection = init_connection("jdbc:postgresql://localhost:5432/postgres", "wyholger", "");
		if (connection == null)
			return;
		UsersRepository users_repository = new UsersRepositoryJdbcImpl(connection);
		ChatroomsRepository chat_rooms_repository = new ChatroomsRepositoryJdbcImpl(connection, users_repository);
		MessagesRepository messages_repository = new MessagesRepositoryJdbcImpl(connection, chat_rooms_repository, users_repository);
		User creator;
		Chatroom room;
		Message message;

		try
		{
			creator = get_user_from_bd_by_index(users_repository, 1L);
			room = get_chatroom_from_bd_by_index(chat_rooms_repository, 1L);
			message = new Message(null, creator, room, "This message from main!#2", LocalDateTime.now());
			messages_repository.save(message);
			System.out.println("ID message generated by the database = " + message.getId());
		}
		catch (NotSavedSubEntityException e)
		{
			System.out.println(e);
		}
	}

	private static User get_user_from_bd_by_index(UsersRepository users_repository, Long id)
	{
		User creator = users_repository.findById(id).orElse(null);
		if (creator == null)
			throw new NotSavedSubEntityException();
		return creator;
	}

	private static Chatroom get_chatroom_from_bd_by_index(ChatroomsRepository chat_rooms_repository, Long id)
	{
		Chatroom room = chat_rooms_repository.findById(id).orElse(null);
		if (room == null)
			throw new NotSavedSubEntityException();
		return room;
	}
}
